services:

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27016:27017"
    command: --quiet
  
  load-mongo:
        build:
          context: ./mongo
          dockerfile: Dockerfile
          args:
            - DB_HOST=mongodb://mongo:27017
            - COLLECTION=articles
            - DB_NAME=articles-challenge
        links:
            - mongo

  # api:
  #   container_name: articles-api
  #   build:
  #     context: ./api
  #     args:
  #       - DB_HOST=mongo
  #   ports:
  #     - 8080:8080
  #   links:
  #     - mongo

  graphql-api:
    container_name: articles-graphql-api
    build:
      context: ./graphql-api
      args:
        - DB_HOST=mongo
    ports:
      - 8080:8080
    links:
      - mongo

  fe:
    container_name: articles-fe
    build:
      context: ./fe
      args:
            - API_URL=http://localhost:8080
    ports:
      - 3000:3000
    links:
      - graphql-api
